= Contributing to Mobile NixOS

You don't need to write code to help contributing with Mobile NixOS.

As Mobile NixOS is a superset on top of NixOS, you should read the link:https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md[
contributing guidelines] of the NixOS project. Many of the points apply just
the same with Mobile NixOS.

== “AI”-assisted contributions

[NOTE]
====
Using pre-existing *boilerplate*, *snippets*, or *syntax suggestions* from your IDE are not considered as “AI”-assisted changes.
====

Contributions written largely with help of LLMs (_Large Language Models_), other “AI” (or non-“AI”), or similar systems are not welcome.
Such systems of concern are generally using statistical models built on “knowledge” acquired for the purpose without express consent, and with disregard of the authorship and attribution.

This includes, but is not limited to:

 - Using them to generate comments
 - Using them to generate documentation
 - Using them to generate code

Contributions should be largely authored by the people in the commit information, e.g. the `Committer,` `Author`, `Signed-off-by`, and `Co-authored-by` fields, exclusively.

If you are unsure, or you had help from automated “AI”-generation in _part_ of your contribution, please tell us when contributing.
It does not mean the contribution will be rejected outright.
We will evaluate on a case-by-case basis.
We value honesty, and take it into consideration.

The same applies to interactions with the repository and community.
Using the output of “AI” as part of your interactions such as issues, pull requests or comments is not welcome.

An exception is made for machine translation of prose, as long as it is clearly outlined that machine translation is used.

== Opening issues

Issues you face when using or working with Mobile NixOS should be filed on
link:https://github.com/mobile-nixos/mobile-nixos/issues[the project's issue tracker].

First verify an existing, open, and recent issue matching your exact problem
doesn't already exist. In case of doubt, always open a new issue. Sometimes
vaguely reported symptoms are from different sources and it is easier to manage
when different issues are opened.

When describing the issues you face, please provide the most information you
can. For sharing logs, please share them as link:https://gist.github.com/[Gists]
so the issue does not get bogged down.

== Porting

ifdef::env-github[]
See the <<doc/porting-guide.adoc#,Device Porting Guide>>.
endif::[]
ifndef::env-github[]
See the <<porting-guide.adoc#,Device Porting Guide>>.
endif::[]

Once a port has been made for a new device, link:https://github.com/mobile-nixos/mobile-nixos/pulls[open a Pull Request].

== Packaging software

Unless it is related to the abstraction of device specifics, packaging should
be done upstream at the link:https://github.com/NixOS/nixpkgs[Nixpkgs] project.

Mobile NixOS is a superset of NixOS, all the software that is in NixOS is
available for Mobile NixOS.
